server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/stores/**, 
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deilveries/**, 
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=/notifyLogs/**, /myDeliveryInfos/**
        - id: point
          uri: http://localhost:8085
          predicates:
            - Path=/points/**, /pointInfos/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/stores/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deilveries/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/notifyLogs/**, /myDeliveryInfos/**
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, /pointInfos/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
