---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "front"
    labels: 
      app: "front"
  spec: 
    selector: 
      matchLabels: 
        app: "front"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "front"
      spec: 
        containers: 
          - 
            name: "front"
            image: "front"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "front"
    labels: 
      app: "front"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "front"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "store"
    labels: 
      app: "store"
  spec: 
    selector: 
      matchLabels: 
        app: "store"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "store"
      spec: 
        containers: 
          - 
            name: "store"
            image: "store"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "store"
    labels: 
      app: "store"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "store"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "delivery"
    labels: 
      app: "delivery"
  spec: 
    selector: 
      matchLabels: 
        app: "delivery"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "delivery"
      spec: 
        containers: 
          - 
            name: "delivery"
            image: "delivery"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "delivery"
    labels: 
      app: "delivery"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "delivery"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "customer"
    labels: 
      app: "customer"
  spec: 
    selector: 
      matchLabels: 
        app: "customer"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "customer"
      spec: 
        containers: 
          - 
            name: "customer"
            image: "customer"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "customer"
    labels: 
      app: "customer"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "customer"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "point"
    labels: 
      app: "point"
  spec: 
    selector: 
      matchLabels: 
        app: "point"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "point"
      spec: 
        containers: 
          - 
            name: "point"
            image: "point"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "point"
    labels: 
      app: "point"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "point"
